### ISSUE TITLE
Why there is no export method as present in the FBX Sdk

### ISSUE THREAD

**Issue by itsmenishantchawla** [izrik/ChamberLib.FbxSharp#3]

**Comment by izrik** [comment]
@itsmenishantchawla Exporting FBX files is beyond the scope of this library. The purpose of `ChamberLib.FbxSharp` is to import FBX files into a game that uses [ChamberLib](https://github.com/izrik/ChamberLib). 

This library has a dependency on [`FbxSharp`](https://github.com/izrik/FbxSharp), which is meant as a pure C# replacement for the FBX SDK. That library currently only imports FBX files, as that is the main use case for making games. My limited understanding is that Autodesk doesn't allow third-party tools to export FBX files. As that's not a main use case right now, it hasn't been implemented yet. But even if it _were_ implemented, it would only be in `FbxSharp`, not in `ChamberLib.FbxSharp`, as it would still be beyond the scope.
